// Auto-generated by bake_fsm.py -- DO NOT EDIT
#pragma once
#include "fsm_types.hpp"

namespace silksong {
namespace fsm_lace_boss1 {

constexpr int NUM_STATES = 88;
constexpr int NUM_ACTIONS = 520;
constexpr int NUM_TRANSITIONS = 127;
constexpr int NUM_PARAMS = 1081;
constexpr int NUM_GLOBAL_TRANSITIONS = 2;
constexpr uint8_t START_STATE = 0;

// Event IDs
enum Event : uint8_t {
    EVT_FINISHED = 0,
    EVT_ATTACK = 1,
    EVT_BIND_BELL = 2,
    EVT_BLOCKED_HIT = 3,
    EVT_CANCEL = 4,
    EVT_CHARGE = 5,
    EVT_CLOSE = 6,
    EVT_COMBO = 7,
    EVT_CONVO_END = 8,
    EVT_COUNTER = 9,
    EVT_CROSS_SLASH = 10,
    EVT_DOCKS = 11,
    EVT_END = 12,
    EVT_ENTER = 13,
    EVT_EVADE = 14,
    EVT_FAR = 15,
    EVT_GROTTO = 16,
    EVT_HERO_COLLIDE = 17,
    EVT_HOP_END = 18,
    EVT_HORNET_DEAD = 19,
    EVT_J_SLASH = 20,
    EVT_LAND = 21,
    EVT_LEAN = 22,
    EVT_MEET = 23,
    EVT_MULTI_HIT_CONNECT = 24,
    EVT_NEXT = 25,
    EVT_RANGE_IN = 26,
    EVT_RANGE_OUT = 27,
    EVT_REFIGHT = 28,
    EVT_REMEET = 29,
    EVT_SING = 30,
    EVT_SING_DURATION_END = 31,
    EVT_STUN = 32,
    EVT_SWISH = 33,
    EVT_TOOK_DAMAGE = 34,
    EVT_UPRIGHT = 35,
    EVT_WAIT = 36,
    EVT_LAVA_DAMAGE = 37,
    EVT_WALL = 38,
    EVT_NONE = 255
};

// State indices (for debugging/reference)
enum StateIdx : uint8_t {
    ST_IDLE = 0,
    ST_CHARGE_ANTIC = 1,
    ST_CHARGE = 2,
    ST_CHARGE_RECOVER = 3,
    ST_J_SLASH_ANTIC = 4,
    ST_J_SLASH_1 = 5,
    ST_DOWNSTAB_ANTIC = 6,
    ST_J_SLASH_2 = 7,
    ST_J_SLASH_3 = 8,
    ST_J_SLASH_4 = 9,
    ST_DOWNSTAB = 10,
    ST_DOWNSTAB_LAND = 11,
    ST_COUNTER_ANTIC = 12,
    ST_COUNTER_STANCE = 13,
    ST_COUNTER_END = 14,
    ST_COUNTER_HIT = 15,
    ST_RAPIDSLASH_CHARGE = 16,
    ST_RAPIDSLASH_LOOP = 17,
    ST_RAPIDSLASH_END = 18,
    ST_COMBOSLASH_1 = 19,
    ST_COMBOSLASH_2 = 20,
    ST_COMBOSLASH_3 = 21,
    ST_COMBOSLASH_4 = 22,
    ST_COMBOSLASH_5 = 23,
    ST_DISTANCE_CHECK = 24,
    ST_CLOSE = 25,
    ST_FAR = 26,
    ST_EVADE = 27,
    ST_EVADE_RECOVER = 28,
    ST_EVADE_MOVE = 29,
    ST_HOP_CHECK = 30,
    ST_HOP_TO_CHARGE = 31,
    ST_HOP_TO_J_SLASH = 32,
    ST_HOP_TO_COMBO = 33,
    ST_HOP_END = 34,
    ST_HOP_ANTIC = 35,
    ST_HOP = 36,
    ST_HOP_RECOVER = 37,
    ST_WILL_COUNTERQ = 38,
    ST_STUN_START = 39,
    ST_STUN_AIR = 40,
    ST_STUNNED = 41,
    ST_STUN_RECOVER = 42,
    ST_CROSSSLASH_ANTIC = 43,
    ST_CROSSSLASH = 44,
    ST_SLASH_SLAM = 45,
    ST_CROSSSLASHQ = 46,
    ST_CROSSSLASH_AIM = 47,
    ST_CS_EVADE = 48,
    ST_CS_EVADE_CANCEL = 49,
    ST_MULTIHITTING = 50,
    ST_MULTIHIT_SLASH = 51,
    ST_HERO_FACING = 52,
    ST_COLLIDE_TO_MULTIHIT = 53,
    ST_POSE = 54,
    ST_FINISH_MULTIHIT = 55,
    ST_STUN_LAND = 56,
    ST_STUN_DAMAGE = 57,
    ST_DAMAGE_RECOVER = 58,
    ST_CHARGE_BREAK = 59,
    ST_COUNTER_DIR = 60,
    ST_POSE_SWISH = 61,
    ST_POSE_LEAN = 62,
    ST_POSE_UPRIGHT = 63,
    ST_POSE_SWISH_2 = 64,
    ST_DEATH_POSE = 65,
    ST_TRAP_STUN = 66,
    ST_COLLIDE_CANCEL = 67,
    ST_RANGE_OUT = 68,
    ST_POSE_SWISH_3 = 69,
    ST_EVADE_2 = 70,
    ST_EVADE_RECOVER_2 = 71,
    ST_RANGE_RETURN = 72,
    ST_SWISH_BLOCK = 73,
    ST_KEEP_EVADINGQ = 74,
    ST_BIND_BELL_DAMAGE = 75,
    ST_SING_ANTIC = 76,
    ST_SING = 77,
    ST_SING_END = 78,
    ST_LAVA_DAMAGE = 79,
    ST_LAVA_HOP = 80,
    ST_LAVA_TELE_OUT = 81,
    ST_SET_TELE_POS_X = 82,
    ST_TELE_IN = 83,
    ST_LAVA_END = 84,
    ST_WALLCLING = 85,
    ST_DSTAB_CONSTRAINQ = 86,
    ST_KICKOFF = 87,
};

// Float variable slots
enum FloatVar : uint8_t {
    FVAR_CENTRE_X = 0, // init=93.77999877929688
    FVAR_COUNTER_PAUSE = 1, // init=0.0
    FVAR_DISTANCE = 2, // init=0.0
    FVAR_GRAVITY = 3, // init=2.0
    FVAR_HERO_Y = 4, // init=0.0
    FVAR_LAND_Y = 5, // init=7.598696231842041
    FVAR_SELF_X = 6, // init=0.0
    FVAR_STUN_TIMER = 7, // init=0.0
    FVAR_TARGET_DISTANCE = 8, // init=0.0
    FVAR_X_SCALE = 9, // init=0.0
    FVAR_LAVA_POS_Y = 10, // init=0.0
    FVAR_CS_LACE_POS_X = 11, // init=0.0
    FVAR_CS_LACE_POS_Y = 12, // init=0.0
    FVAR_CS_LACE_POS_Z = 13, // init=0.0
    FVAR_MULTIHIT_POS_X = 14, // init=0.0
    FVAR_MULTIHIT_POS_Y = 15, // init=0.0
    FVAR_MULTIHIT_POS_Z = 16, // init=0.0
    NUM_FLOAT_VARS = 17
};

// Int variable slots
enum IntVar : uint8_t {
    IVAR_CT_CHARGE = 0, // init=0
    IVAR_CT_COMBO = 1, // init=0
    IVAR_CT_CROSSSLASH = 2, // init=0
    IVAR_CT_EVADE = 3, // init=0
    IVAR_CT_J_SLASH = 4, // init=0
    IVAR_EVADE_ATTEMPTS = 5, // init=0
    IVAR_HOPS = 6, // init=0
    IVAR_INVINCIBILITY_DIRECTION = 7, // init=0
    IVAR_MS_CHARGE = 8, // init=0
    IVAR_MS_COMBO = 9, // init=0
    IVAR_MS_EVADE = 10, // init=0
    IVAR_MS_J_SLASH = 11, // init=0
    IVAR_RAGE_HP = 12, // init=125
    IVAR_NEXTEVENTID = 13, // init=0
    NUM_INT_VARS = 14
};

// Bool variable slots
enum BoolVar : uint8_t {
    BVAR_COUNTER_RANGE = 0, // init=0
    BVAR_COUNTER_READY = 1, // init=0
    BVAR_CROSSSLASHING_HERO = 2, // init=0
    BVAR_DO_POSE = 3, // init=0
    BVAR_FACING_RIGHT = 4, // init=0
    BVAR_HERO_IS_RIGHT = 5, // init=0
    BVAR_HORNET_DEAD = 6, // init=0
    BVAR_LACE_IS_RIGHT = 7, // init=0
    BVAR_NEEDOLIN_FIGHT = 8, // init=0
    BVAR_RIGHT_SIDE = 9, // init=0
    BVAR_WILL_COUNTER = 10, // init=0
    BVAR_WILL_CROSSSLASH = 11, // init=0
    BVAR_BIND_BELL_HIT = 12, // init=0
    BVAR_NPC_BLOCKED_HIT = 13, // init=0
    BVAR_DORMANT_BLOCK = 14, // init=0
    BVAR_ABOVE_WALLCLING_MIN = 15, // init=0
    BVAR_NOT_ABOVE_HERO = 16, // init=0
    BVAR_WALL_AHEAD = 17, // init=0
    BVAR_BELOW_GROUND = 18, // init=0
    NUM_BOOL_VARS = 19
};

// Initial float variable values
constexpr float INIT_FLOAT_VARS[] = {
    93.77999877929688f, // Centre X
    0.0f, // Counter Pause
    0.0f, // Distance
    2.0f, // Gravity
    0.0f, // Hero Y
    7.598696231842041f, // Land Y
    0.0f, // Self X
    0.0f, // Stun Timer
    0.0f, // Target Distance
    0.0f, // X Scale
    0.0f, // Lava Pos Y
    0.0f, // CS Lace Pos.x
    0.0f, // CS Lace Pos.y
    0.0f, // CS Lace Pos.z
    0.0f, // Multihit Pos.x
    0.0f, // Multihit Pos.y
    0.0f, // Multihit Pos.z
};

// Initial int variable values
constexpr int32_t INIT_INT_VARS[] = {
    0, // Ct Charge
    0, // Ct Combo
    0, // Ct CrossSlash
    0, // Ct Evade
    0, // Ct J Slash
    0, // Evade Attempts
    0, // Hops
    0, // Invincibility Direction
    0, // Ms Charge
    0, // Ms Combo
    0, // Ms Evade
    0, // Ms J Slash
    125, // Rage HP
    0, // $NextEventId
};

// Initial bool variable values
constexpr uint8_t INIT_BOOL_VARS[] = {
    0, // Counter Range
    0, // Counter Ready
    0, // CrossSlashing Hero
    0, // Do Pose
    0, // Facing Right
    0, // Hero Is Right
    0, // Hornet Dead
    0, // Lace Is Right
    0, // Needolin Fight
    0, // Right Side
    0, // Will Counter
    0, // Will CrossSlash
    0, // Bind Bell Hit
    0, // NPC Blocked Hit
    0, // Dormant Block
    0, // Above Wallcling Min
    0, // Not Above Hero
    0, // Wall Ahead
    0, // Below Ground
};

constexpr FsmStateDef STATES[] = {
    { 0, 11, 0, 5, 0, {0, 0} }, // [0] Idle
    { 11, 8, 5, 1, 1, {0, 0} }, // [1] Charge Antic
    { 19, 10, 6, 1, 2, {0, 0} }, // [2] Charge
    { 29, 4, 7, 1, 3, {0, 0} }, // [3] Charge Recover
    { 33, 5, 8, 1, 4, {0, 0} }, // [4] J Slash Antic
    { 38, 8, 9, 1, 5, {0, 0} }, // [5] J Slash 1
    { 46, 4, 10, 1, 6, {0, 0} }, // [6] Downstab Antic
    { 50, 4, 11, 1, 7, {0, 0} }, // [7] J Slash 2
    { 54, 4, 12, 1, 8, {0, 0} }, // [8] J Slash 3
    { 58, 3, 13, 1, 9, {0, 0} }, // [9] J Slash 4
    { 61, 15, 14, 2, 10, {0, 0} }, // [10] Downstab
    { 76, 13, 16, 2, 11, {0, 0} }, // [11] Downstab Land
    { 89, 5, 18, 1, 12, {0, 0} }, // [12] Counter Antic
    { 94, 7, 19, 2, 13, {0, 0} }, // [13] Counter Stance
    { 101, 3, 21, 1, 14, {0, 0} }, // [14] Counter End
    { 104, 8, 22, 1, 15, {0, 0} }, // [15] Counter Hit
    { 112, 7, 23, 2, 16, {0, 0} }, // [16] RapidSlash Charge
    { 119, 9, 25, 2, 17, {0, 0} }, // [17] RapidSlash Loop
    { 128, 6, 27, 1, 18, {0, 0} }, // [18] RapidSlash End
    { 134, 5, 28, 1, 19, {0, 0} }, // [19] ComboSlash 1
    { 139, 9, 29, 1, 20, {0, 0} }, // [20] ComboSlash 2
    { 148, 5, 30, 1, 21, {0, 0} }, // [21] ComboSlash 3
    { 153, 9, 31, 1, 22, {0, 0} }, // [22] ComboSlash 4
    { 162, 6, 32, 1, 23, {0, 0} }, // [23] ComboSlash 5
    { 168, 3, 33, 3, 24, {0, 0} }, // [24] Distance Check
    { 171, 2, 36, 4, 25, {0, 0} }, // [25] Close
    { 173, 3, 40, 3, 26, {0, 0} }, // [26] Far
    { 176, 6, 43, 1, 27, {0, 0} }, // [27] Evade
    { 182, 3, 44, 1, 28, {0, 0} }, // [28] Evade Recover
    { 185, 2, 45, 4, 29, {0, 0} }, // [29] Evade Move
    { 187, 4, 49, 2, 30, {0, 0} }, // [30] Hop Check
    { 191, 3, 51, 1, 31, {0, 0} }, // [31] Hop To Charge
    { 194, 3, 52, 1, 32, {0, 0} }, // [32] Hop To J Slash
    { 197, 3, 53, 1, 33, {0, 0} }, // [33] Hop To Combo
    { 200, 1, 54, 3, 34, {0, 0} }, // [34] Hop End
    { 201, 4, 57, 1, 35, {0, 0} }, // [35] Hop Antic
    { 205, 5, 58, 1, 36, {0, 0} }, // [36] Hop
    { 210, 4, 59, 1, 37, {0, 0} }, // [37] Hop Recover
    { 214, 2, 60, 1, 38, {0, 0} }, // [38] Will Counter?
    { 216, 23, 61, 1, 39, {0, 0} }, // [39] Stun Start
    { 239, 4, 62, 1, 40, {0, 0} }, // [40] Stun Air
    { 243, 4, 63, 3, 41, {0, 0} }, // [41] Stunned
    { 247, 7, 66, 1, 42, {0, 0} }, // [42] Stun Recover
    { 254, 12, 67, 1, 43, {0, 0} }, // [43] CrossSlash Antic
    { 266, 12, 68, 1, 44, {0, 0} }, // [44] CrossSlash
    { 278, 16, 69, 1, 45, {0, 0} }, // [45] Slash Slam
    { 294, 4, 70, 2, 46, {0, 0} }, // [46] CrossSlash?
    { 298, 12, 72, 2, 47, {0, 0} }, // [47] CrossSlash Aim
    { 310, 4, 74, 2, 48, {0, 0} }, // [48] CS Evade
    { 314, 7, 76, 1, 49, {0, 0} }, // [49] CS Evade Cancel
    { 321, 10, 77, 1, 50, {0, 0} }, // [50] Multihitting
    { 331, 11, 78, 1, 51, {0, 0} }, // [51] Multihit Slash
    { 342, 3, 79, 1, 52, {0, 0} }, // [52] Hero Facing
    { 345, 10, 80, 3, 53, {0, 0} }, // [53] Collide To Multihit
    { 355, 5, 83, 5, 54, {0, 0} }, // [54] Pose
    { 360, 10, 88, 1, 55, {0, 0} }, // [55] Finish Multihit
    { 370, 9, 89, 1, 56, {0, 0} }, // [56] Stun Land
    { 379, 7, 90, 2, 57, {0, 0} }, // [57] Stun Damage
    { 386, 3, 92, 1, 58, {0, 0} }, // [58] Damage Recover
    { 389, 2, 93, 1, 59, {0, 0} }, // [59] Charge Break
    { 391, 3, 94, 1, 60, {0, 0} }, // [60] Counter Dir
    { 394, 5, 95, 2, 61, {0, 0} }, // [61] Pose Swish
    { 399, 4, 97, 1, 62, {0, 0} }, // [62] Pose Lean
    { 403, 3, 98, 1, 63, {0, 0} }, // [63] Pose Upright
    { 406, 3, 99, 1, 64, {0, 0} }, // [64] Pose Swish 2
    { 409, 6, 100, 1, 65, {0, 0} }, // [65] Death Pose
    { 415, 3, 101, 1, 66, {0, 0} }, // [66] Trap Stun
    { 418, 2, 102, 1, 67, {0, 0} }, // [67] Collide Cancel
    { 420, 7, 103, 3, 68, {0, 0} }, // [68] Range Out
    { 427, 2, 106, 1, 69, {0, 0} }, // [69] Pose Swish 3
    { 429, 6, 107, 1, 70, {0, 0} }, // [70] Evade 2
    { 435, 3, 108, 1, 71, {0, 0} }, // [71] Evade Recover 2
    { 438, 3, 109, 1, 72, {0, 0} }, // [72] Range Return
    { 441, 3, 110, 1, 73, {0, 0} }, // [73] Swish Block
    { 444, 4, 111, 2, 74, {0, 0} }, // [74] Keep Evading?
    { 448, 1, 113, 1, 75, {0, 0} }, // [75] Bind Bell Damage
    { 449, 5, 114, 1, 76, {0, 0} }, // [76] Sing Antic
    { 454, 2, 115, 2, 77, {0, 0} }, // [77] Sing
    { 456, 2, 117, 1, 78, {0, 0} }, // [78] Sing End
    { 458, 20, 118, 1, 79, {0, 0} }, // [79] Lava Damage
    { 478, 9, 119, 1, 80, {0, 0} }, // [80] Lava Hop
    { 487, 4, 120, 1, 81, {0, 0} }, // [81] Lava Tele Out
    { 491, 6, 121, 1, 82, {0, 0} }, // [82] Set Tele Pos X
    { 497, 2, 122, 1, 83, {0, 0} }, // [83] Tele In
    { 499, 8, 123, 1, 84, {0, 0} }, // [84] Lava End
    { 507, 5, 124, 1, 85, {0, 0} }, // [85] Wallcling
    { 512, 4, 125, 1, 86, {0, 0} }, // [86] Dstab Constrain?
    { 516, 4, 126, 1, 87, {0, 0} }, // [87] Kickoff
};

constexpr FsmActionDef ACTIONS[] = {
    { FsmActionType::Wait, 1, 0 }, // [0]
    { FsmActionType::FaceObjectV4, 0, 2 }, // [1]
    { FsmActionType::GetDistance, 1, 4 }, // [2]
    { FsmActionType::EaseFloat, 1, 5 }, // [3]
    { FsmActionType::FloatTestToBool, 0, 13 }, // [4]
    { FsmActionType::FloatTestToBool, 0, 19 }, // [5]
    { FsmActionType::BoolAllTrue, 1, 25 }, // [6]
    { FsmActionType::CheckAlertRange, 1, 30 }, // [7]
    { FsmActionType::CheckHeroPerformanceRegionV2, 1, 35 }, // [8]
    { FsmActionType::Wait, 1, 44 }, // [9]
    { FsmActionType::SetHitboxGeometry, 0, 46 }, // [10]
    { FsmActionType::FaceObjectV2, 0, 51 }, // [11]
    { FsmActionType::SetVelocityByScale, 0, 52 }, // [12]
    { FsmActionType::DecelerateXY, 1, 54 }, // [13]
    { FsmActionType::Noop, 0, 56 }, // [14]
    { FsmActionType::Wait, 1, 56 }, // [15]
    { FsmActionType::Noop, 0, 58 }, // [16]
    { FsmActionType::Noop, 0, 58 }, // [17]
    { FsmActionType::SetHitboxGeometry, 0, 58 }, // [18]
    { FsmActionType::Noop, 0, 63 }, // [19]
    { FsmActionType::SetVelocityByScale, 0, 63 }, // [20]
    { FsmActionType::Wait, 1, 65 }, // [21]
    { FsmActionType::Noop, 0, 67 }, // [22]
    { FsmActionType::Noop, 0, 67 }, // [23]
    { FsmActionType::DecelerateXY, 1, 67 }, // [24]
    { FsmActionType::Noop, 0, 69 }, // [25]
    { FsmActionType::Noop, 0, 69 }, // [26]
    { FsmActionType::Noop, 0, 69 }, // [27]
    { FsmActionType::SetHitboxGeometry, 0, 69 }, // [28]
    { FsmActionType::SetBoolValue, 0, 74 }, // [29]
    { FsmActionType::Wait, 1, 76 }, // [30]
    { FsmActionType::DecelerateXY, 1, 78 }, // [31]
    { FsmActionType::SetHitboxGeometry, 0, 80 }, // [32]
    { FsmActionType::FaceObjectV2, 0, 85 }, // [33]
    { FsmActionType::Noop, 0, 86 }, // [34]
    { FsmActionType::Wait, 1, 86 }, // [35]
    { FsmActionType::Noop, 0, 88 }, // [36]
    { FsmActionType::SetHitboxGeometry, 0, 88 }, // [37]
    { FsmActionType::Noop, 0, 93 }, // [38]
    { FsmActionType::Wait, 1, 93 }, // [39]
    { FsmActionType::SetGravity2dScale, 0, 95 }, // [40]
    { FsmActionType::SetVelocityByScale, 0, 96 }, // [41]
    { FsmActionType::DecelerateXY, 1, 98 }, // [42]
    { FsmActionType::Noop, 0, 100 }, // [43]
    { FsmActionType::Noop, 0, 100 }, // [44]
    { FsmActionType::SetHitboxGeometry, 0, 100 }, // [45]
    { FsmActionType::FaceObjectV2, 0, 105 }, // [46]
    { FsmActionType::DecelerateXY, 1, 106 }, // [47]
    { FsmActionType::Wait, 1, 108 }, // [48]
    { FsmActionType::SetHitboxGeometry, 0, 110 }, // [49]
    { FsmActionType::Wait, 1, 115 }, // [50]
    { FsmActionType::Noop, 0, 117 }, // [51]
    { FsmActionType::DecelerateXY, 1, 117 }, // [52]
    { FsmActionType::SetHitboxGeometry, 0, 119 }, // [53]
    { FsmActionType::Wait, 1, 124 }, // [54]
    { FsmActionType::Noop, 0, 126 }, // [55]
    { FsmActionType::DecelerateXY, 1, 126 }, // [56]
    { FsmActionType::SetHitboxGeometry, 0, 128 }, // [57]
    { FsmActionType::Wait, 1, 133 }, // [58]
    { FsmActionType::DecelerateXY, 1, 135 }, // [59]
    { FsmActionType::SetHitboxGeometry, 0, 137 }, // [60]
    { FsmActionType::Noop, 0, 142 }, // [61]
    { FsmActionType::Noop, 0, 142 }, // [62]
    { FsmActionType::Noop, 0, 142 }, // [63]
    { FsmActionType::Noop, 0, 142 }, // [64]
    { FsmActionType::SetVelocityByScale, 0, 142 }, // [65]
    { FsmActionType::Noop, 0, 144 }, // [66]
    { FsmActionType::CheckIsCharacterGrounded, 1, 144 }, // [67]
    { FsmActionType::CheckCollisionSideEnter, 1, 147 }, // [68]
    { FsmActionType::Noop, 0, 151 }, // [69]
    { FsmActionType::RayCast2dV2, 1, 151 }, // [70]
    { FsmActionType::CheckTargetDirection, 1, 158 }, // [71]
    { FsmActionType::BoolAllTrue, 1, 168 }, // [72]
    { FsmActionType::CheckYPositionV2, 1, 173 }, // [73]
    { FsmActionType::BoolAllTrue, 1, 182 }, // [74]
    { FsmActionType::SetHitboxGeometry, 0, 186 }, // [75]
    { FsmActionType::GetPosition2d, 0, 191 }, // [76]
    { FsmActionType::FloatInRange, 0, 193 }, // [77]
    { FsmActionType::SetPosition2d, 0, 199 }, // [78]
    { FsmActionType::Noop, 0, 201 }, // [79]
    { FsmActionType::Noop, 0, 201 }, // [80]
    { FsmActionType::SetGravity2dScale, 0, 201 }, // [81]
    { FsmActionType::Wait, 1, 202 }, // [82]
    { FsmActionType::SetVelocity2d, 0, 204 }, // [83]
    { FsmActionType::DecelerateXY, 1, 206 }, // [84]
    { FsmActionType::Noop, 0, 208 }, // [85]
    { FsmActionType::SetBoolValue, 0, 208 }, // [86]
    { FsmActionType::Noop, 0, 210 }, // [87]
    { FsmActionType::SetHitboxGeometry, 0, 210 }, // [88]
    { FsmActionType::SetBoolValue, 0, 215 }, // [89]
    { FsmActionType::FaceObjectV2, 0, 217 }, // [90]
    { FsmActionType::Wait, 1, 218 }, // [91]
    { FsmActionType::Noop, 0, 220 }, // [92]
    { FsmActionType::SetHitboxGeometry, 0, 220 }, // [93]
    { FsmActionType::Noop, 0, 225 }, // [94]
    { FsmActionType::SetInvincible, 0, 225 }, // [95]
    { FsmActionType::Wait, 1, 228 }, // [96]
    { FsmActionType::Noop, 0, 230 }, // [97]
    { FsmActionType::Noop, 0, 230 }, // [98]
    { FsmActionType::Noop, 0, 230 }, // [99]
    { FsmActionType::SetHitboxGeometry, 0, 230 }, // [100]
    { FsmActionType::Wait, 1, 235 }, // [101]
    { FsmActionType::SetBoolValue, 0, 237 }, // [102]
    { FsmActionType::SetHitboxGeometry, 0, 239 }, // [103]
    { FsmActionType::FaceObjectV2, 0, 244 }, // [104]
    { FsmActionType::Wait, 1, 245 }, // [105]
    { FsmActionType::Noop, 0, 247 }, // [106]
    { FsmActionType::Noop, 0, 247 }, // [107]
    { FsmActionType::Noop, 0, 247 }, // [108]
    { FsmActionType::Noop, 0, 247 }, // [109]
    { FsmActionType::Noop, 0, 247 }, // [110]
    { FsmActionType::SetHitboxGeometry, 0, 247 }, // [111]
    { FsmActionType::Wait, 1, 252 }, // [112]
    { FsmActionType::SetVelocityByScale, 0, 254 }, // [113]
    { FsmActionType::SetDamageHeroAmount, 0, 256 }, // [114]
    { FsmActionType::Noop, 0, 257 }, // [115]
    { FsmActionType::Noop, 0, 257 }, // [116]
    { FsmActionType::Noop, 0, 257 }, // [117]
    { FsmActionType::SetHitboxGeometry, 0, 257 }, // [118]
    { FsmActionType::DecelerateXY, 1, 262 }, // [119]
    { FsmActionType::Noop, 0, 264 }, // [120]
    { FsmActionType::Wait, 1, 264 }, // [121]
    { FsmActionType::SendEventByNameV2, 0, 266 }, // [122]
    { FsmActionType::Noop, 0, 268 }, // [123]
    { FsmActionType::Noop, 0, 268 }, // [124]
    { FsmActionType::SetPolygonCollider, 0, 268 }, // [125]
    { FsmActionType::Noop, 0, 270 }, // [126]
    { FsmActionType::SetHitboxGeometry, 0, 270 }, // [127]
    { FsmActionType::Wait, 1, 275 }, // [128]
    { FsmActionType::Noop, 0, 277 }, // [129]
    { FsmActionType::SetDamageHeroAmount, 0, 277 }, // [130]
    { FsmActionType::SetBoolValue, 0, 278 }, // [131]
    { FsmActionType::Noop, 0, 280 }, // [132]
    { FsmActionType::SetHitboxGeometry, 0, 280 }, // [133]
    { FsmActionType::FaceObjectV2, 0, 285 }, // [134]
    { FsmActionType::Wait, 1, 286 }, // [135]
    { FsmActionType::Noop, 0, 288 }, // [136]
    { FsmActionType::Noop, 0, 288 }, // [137]
    { FsmActionType::SetHitboxGeometry, 0, 288 }, // [138]
    { FsmActionType::Noop, 0, 293 }, // [139]
    { FsmActionType::Noop, 0, 293 }, // [140]
    { FsmActionType::SetVelocityByScale, 0, 293 }, // [141]
    { FsmActionType::Noop, 0, 295 }, // [142]
    { FsmActionType::Wait, 1, 295 }, // [143]
    { FsmActionType::Noop, 0, 297 }, // [144]
    { FsmActionType::Noop, 0, 297 }, // [145]
    { FsmActionType::Noop, 0, 297 }, // [146]
    { FsmActionType::SetHitboxGeometry, 0, 297 }, // [147]
    { FsmActionType::Noop, 0, 302 }, // [148]
    { FsmActionType::Wait, 1, 302 }, // [149]
    { FsmActionType::DecelerateXY, 1, 304 }, // [150]
    { FsmActionType::Noop, 0, 306 }, // [151]
    { FsmActionType::SetHitboxGeometry, 0, 306 }, // [152]
    { FsmActionType::Noop, 0, 311 }, // [153]
    { FsmActionType::Noop, 0, 311 }, // [154]
    { FsmActionType::SetVelocityByScale, 0, 311 }, // [155]
    { FsmActionType::Noop, 0, 313 }, // [156]
    { FsmActionType::Wait, 1, 313 }, // [157]
    { FsmActionType::Noop, 0, 315 }, // [158]
    { FsmActionType::Noop, 0, 315 }, // [159]
    { FsmActionType::Noop, 0, 315 }, // [160]
    { FsmActionType::SetHitboxGeometry, 0, 315 }, // [161]
    { FsmActionType::Noop, 0, 320 }, // [162]
    { FsmActionType::Wait, 1, 320 }, // [163]
    { FsmActionType::SetBoolValue, 0, 322 }, // [164]
    { FsmActionType::DecelerateXY, 1, 324 }, // [165]
    { FsmActionType::Noop, 0, 326 }, // [166]
    { FsmActionType::SetHitboxGeometry, 0, 326 }, // [167]
    { FsmActionType::CheckHeroPerformanceRegionV2, 1, 331 }, // [168]
    { FsmActionType::GetDistance, 1, 340 }, // [169]
    { FsmActionType::FloatCompare, 0, 341 }, // [170]
    { FsmActionType::CheckAlertRange, 1, 347 }, // [171]
    { FsmActionType::SendRandomEventV3, 0, 352 }, // [172]
    { FsmActionType::SetIntValue, 0, 365 }, // [173]
    { FsmActionType::CheckAlertRange, 1, 367 }, // [174]
    { FsmActionType::SendRandomEventV3, 0, 372 }, // [175]
    { FsmActionType::FaceObjectV2, 0, 385 }, // [176]
    { FsmActionType::SetVelocityByScale, 0, 386 }, // [177]
    { FsmActionType::Wait, 1, 388 }, // [178]
    { FsmActionType::Noop, 0, 390 }, // [179]
    { FsmActionType::Noop, 0, 390 }, // [180]
    { FsmActionType::SetHitboxGeometry, 0, 390 }, // [181]
    { FsmActionType::SetVelocity2d, 0, 395 }, // [182]
    { FsmActionType::Wait, 1, 397 }, // [183]
    { FsmActionType::SetHitboxGeometry, 0, 399 }, // [184]
    { FsmActionType::BoolTest, 0, 404 }, // [185]
    { FsmActionType::SendRandomEvent, 0, 407 }, // [186]
    { FsmActionType::GetXDistance, 1, 414 }, // [187]
    { FsmActionType::FloatCompare, 0, 415 }, // [188]
    { FsmActionType::CheckAlertRange, 1, 421 }, // [189]
    { FsmActionType::IntCompare, 0, 426 }, // [190]
    { FsmActionType::SetFloatValue, 0, 431 }, // [191]
    { FsmActionType::SetStringValue, 0, 433 }, // [192]
    { FsmActionType::SetIntValue, 0, 433 }, // [193]
    { FsmActionType::SetFloatValue, 0, 435 }, // [194]
    { FsmActionType::SetStringValue, 0, 437 }, // [195]
    { FsmActionType::SetIntValue, 0, 437 }, // [196]
    { FsmActionType::SetFloatValue, 0, 439 }, // [197]
    { FsmActionType::SetStringValue, 0, 441 }, // [198]
    { FsmActionType::SetIntValue, 0, 441 }, // [199]
    { FsmActionType::SendEvent, 0, 445 }, // [200]
    { FsmActionType::IntAdd, 0, 447 }, // [201]
    { FsmActionType::FaceObjectV2, 0, 449 }, // [202]
    { FsmActionType::Wait, 1, 450 }, // [203]
    { FsmActionType::SetHitboxGeometry, 0, 452 }, // [204]
    { FsmActionType::SetVelocityByScale, 0, 457 }, // [205]
    { FsmActionType::Wait, 1, 459 }, // [206]
    { FsmActionType::Noop, 0, 461 }, // [207]
    { FsmActionType::Noop, 0, 461 }, // [208]
    { FsmActionType::SetHitboxGeometry, 0, 461 }, // [209]
    { FsmActionType::Wait, 1, 466 }, // [210]
    { FsmActionType::DecelerateXY, 1, 468 }, // [211]
    { FsmActionType::Noop, 0, 470 }, // [212]
    { FsmActionType::SetHitboxGeometry, 0, 470 }, // [213]
    { FsmActionType::SendRandomEvent, 0, 475 }, // [214]
    { FsmActionType::SetBoolValue, 0, 480 }, // [215]
    { FsmActionType::Noop, 0, 482 }, // [216]
    { FsmActionType::Noop, 0, 482 }, // [217]
    { FsmActionType::SetRecoilSpeed, 0, 482 }, // [218]
    { FsmActionType::SetFloatValue, 0, 483 }, // [219]
    { FsmActionType::SetGravity2dScale, 0, 485 }, // [220]
    { FsmActionType::FaceObjectV2, 0, 486 }, // [221]
    { FsmActionType::Noop, 0, 487 }, // [222]
    { FsmActionType::SetVelocityByScale, 0, 487 }, // [223]
    { FsmActionType::NextFrameEvent, 1, 489 }, // [224]
    { FsmActionType::Noop, 0, 490 }, // [225]
    { FsmActionType::Noop, 0, 490 }, // [226]
    { FsmActionType::Noop, 0, 490 }, // [227]
    { FsmActionType::Noop, 0, 490 }, // [228]
    { FsmActionType::Noop, 0, 490 }, // [229]
    { FsmActionType::Noop, 0, 490 }, // [230]
    { FsmActionType::SetPolygonCollider, 0, 490 }, // [231]
    { FsmActionType::Noop, 0, 492 }, // [232]
    { FsmActionType::Noop, 0, 492 }, // [233]
    { FsmActionType::Noop, 0, 492 }, // [234]
    { FsmActionType::Noop, 0, 492 }, // [235]
    { FsmActionType::SetHitEffectOrigin, 0, 492 }, // [236]
    { FsmActionType::SendEventByName, 0, 492 }, // [237]
    { FsmActionType::SetHitboxGeometry, 0, 494 }, // [238]
    { FsmActionType::CheckCollisionSideEnter, 1, 499 }, // [239]
    { FsmActionType::CheckCollisionSide, 1, 503 }, // [240]
    { FsmActionType::SetDamageHeroAmount, 0, 507 }, // [241]
    { FsmActionType::SetSpecialDeath, 0, 508 }, // [242]
    { FsmActionType::DecelerateXY, 1, 509 }, // [243]
    { FsmActionType::FloatAdd, 1, 511 }, // [244]
    { FsmActionType::FloatCompare, 0, 513 }, // [245]
    { FsmActionType::CheckHeroPerformanceRegionV2, 1, 519 }, // [246]
    { FsmActionType::SetRecoilSpeed, 0, 528 }, // [247]
    { FsmActionType::SendEventByName, 0, 529 }, // [248]
    { FsmActionType::Wait, 1, 531 }, // [249]
    { FsmActionType::SetBoolValue, 0, 533 }, // [250]
    { FsmActionType::Noop, 0, 535 }, // [251]
    { FsmActionType::Noop, 0, 535 }, // [252]
    { FsmActionType::SetHitboxGeometry, 0, 535 }, // [253]
    { FsmActionType::SetIntValue, 0, 540 }, // [254]
    { FsmActionType::SendEventByName, 0, 542 }, // [255]
    { FsmActionType::RandomInt, 0, 544 }, // [256]
    { FsmActionType::Noop, 0, 548 }, // [257]
    { FsmActionType::SetRecoilSpeed, 0, 548 }, // [258]
    { FsmActionType::SendEventByName, 0, 549 }, // [259]
    { FsmActionType::Noop, 0, 551 }, // [260]
    { FsmActionType::Noop, 0, 551 }, // [261]
    { FsmActionType::Wait, 1, 551 }, // [262]
    { FsmActionType::Noop, 0, 553 }, // [263]
    { FsmActionType::Noop, 0, 553 }, // [264]
    { FsmActionType::SetHitboxGeometry, 0, 553 }, // [265]
    { FsmActionType::SetIsKinematic2d, 0, 558 }, // [266]
    { FsmActionType::SetSpecialDeath, 0, 559 }, // [267]
    { FsmActionType::Noop, 0, 560 }, // [268]
    { FsmActionType::SetCollider, 0, 560 }, // [269]
    { FsmActionType::Wait, 1, 562 }, // [270]
    { FsmActionType::Noop, 0, 564 }, // [271]
    { FsmActionType::SendEventByName, 0, 564 }, // [272]
    { FsmActionType::Noop, 0, 566 }, // [273]
    { FsmActionType::Noop, 0, 566 }, // [274]
    { FsmActionType::GetPosition2d, 0, 566 }, // [275]
    { FsmActionType::SetHitEffectOrigin, 0, 568 }, // [276]
    { FsmActionType::SetHitboxGeometry, 0, 568 }, // [277]
    { FsmActionType::Translate, 1, 573 }, // [278]
    { FsmActionType::Noop, 0, 576 }, // [279]
    { FsmActionType::SendEventByName, 0, 576 }, // [280]
    { FsmActionType::SetRecoilSpeed, 0, 578 }, // [281]
    { FsmActionType::SetSpecialDeath, 0, 579 }, // [282]
    { FsmActionType::Wait, 1, 580 }, // [283]
    { FsmActionType::Noop, 0, 582 }, // [284]
    { FsmActionType::Noop, 0, 582 }, // [285]
    { FsmActionType::SetIsKinematic2d, 0, 582 }, // [286]
    { FsmActionType::Noop, 0, 583 }, // [287]
    { FsmActionType::SetCollider, 0, 583 }, // [288]
    { FsmActionType::Noop, 0, 585 }, // [289]
    { FsmActionType::Noop, 0, 585 }, // [290]
    { FsmActionType::SendEventByName, 0, 585 }, // [291]
    { FsmActionType::SetBoolValue, 0, 587 }, // [292]
    { FsmActionType::SetHitboxGeometry, 0, 589 }, // [293]
    { FsmActionType::Noop, 0, 594 }, // [294]
    { FsmActionType::CompareHP, 1, 594 }, // [295]
    { FsmActionType::IntCompare, 0, 598 }, // [296]
    { FsmActionType::IntAdd, 0, 603 }, // [297]
    { FsmActionType::SetBoolValue, 0, 605 }, // [298]
    { FsmActionType::FaceObjectV2, 0, 607 }, // [299]
    { FsmActionType::GetXDistance, 1, 608 }, // [300]
    { FsmActionType::FloatCompare, 0, 609 }, // [301]
    { FsmActionType::GetPosition2d, 0, 615 }, // [302]
    { FsmActionType::FloatTestToBool, 0, 617 }, // [303]
    { FsmActionType::GetScale, 0, 623 }, // [304]
    { FsmActionType::FloatTestToBool, 0, 626 }, // [305]
    { FsmActionType::BoolTestMulti, 1, 632 }, // [306]
    { FsmActionType::BoolTestMulti, 1, 638 }, // [307]
    { FsmActionType::Noop, 0, 644 }, // [308]
    { FsmActionType::Noop, 0, 644 }, // [309]
    { FsmActionType::SetBoolValue, 0, 644 }, // [310]
    { FsmActionType::IntAdd, 0, 646 }, // [311]
    { FsmActionType::IntCompare, 0, 648 }, // [312]
    { FsmActionType::SetHitboxGeometry, 0, 653 }, // [313]
    { FsmActionType::SetScale, 0, 658 }, // [314]
    { FsmActionType::GetPosition2d, 0, 659 }, // [315]
    { FsmActionType::Noop, 0, 661 }, // [316]
    { FsmActionType::Noop, 0, 661 }, // [317]
    { FsmActionType::FloatCompare, 0, 661 }, // [318]
    { FsmActionType::SetScale, 0, 667 }, // [319]
    { FsmActionType::SetHitboxGeometry, 0, 668 }, // [320]
    { FsmActionType::SetVelocity2d, 0, 673 }, // [321]
    { FsmActionType::SetVelocity2d, 0, 675 }, // [322]
    { FsmActionType::Noop, 0, 677 }, // [323]
    { FsmActionType::Noop, 0, 677 }, // [324]
    { FsmActionType::GetPosition2d, 0, 677 }, // [325]
    { FsmActionType::Noop, 0, 679 }, // [326]
    { FsmActionType::AnimatePositionTo, 1, 679 }, // [327]
    { FsmActionType::Noop, 0, 684 }, // [328]
    { FsmActionType::Wait, 1, 684 }, // [329]
    { FsmActionType::SetHitboxGeometry, 0, 686 }, // [330]
    { FsmActionType::Translate, 1, 691 }, // [331]
    { FsmActionType::Noop, 0, 694 }, // [332]
    { FsmActionType::Noop, 0, 694 }, // [333]
    { FsmActionType::Noop, 0, 694 }, // [334]
    { FsmActionType::Noop, 0, 694 }, // [335]
    { FsmActionType::Wait, 1, 694 }, // [336]
    { FsmActionType::DamageHeroDirectly, 0, 696 }, // [337]
    { FsmActionType::SendEventByName, 0, 697 }, // [338]
    { FsmActionType::SetDamageHeroAmount, 0, 699 }, // [339]
    { FsmActionType::SetBoolValue, 0, 700 }, // [340]
    { FsmActionType::SetHitboxGeometry, 0, 702 }, // [341]
    { FsmActionType::Noop, 0, 707 }, // [342]
    { FsmActionType::CheckTargetDirection, 1, 707 }, // [343]
    { FsmActionType::Noop, 0, 717 }, // [344]
    { FsmActionType::Noop, 0, 717 }, // [345]
    { FsmActionType::BoolTest, 0, 717 }, // [346]
    { FsmActionType::CanHeroTakeDamage, 0, 720 }, // [347]
    { FsmActionType::Noop, 0, 722 }, // [348]
    { FsmActionType::Noop, 0, 722 }, // [349]
    { FsmActionType::SendEventByName, 0, 722 }, // [350]
    { FsmActionType::Noop, 0, 724 }, // [351]
    { FsmActionType::SendEventByNameV2, 0, 724 }, // [352]
    { FsmActionType::Noop, 0, 726 }, // [353]
    { FsmActionType::SetHitboxGeometry, 0, 726 }, // [354]
    { FsmActionType::BoolTest, 0, 731 }, // [355]
    { FsmActionType::Noop, 0, 734 }, // [356]
    { FsmActionType::BoolTest, 0, 734 }, // [357]
    { FsmActionType::SendRandomEvent, 0, 737 }, // [358]
    { FsmActionType::SetHitboxGeometry, 0, 744 }, // [359]
    { FsmActionType::SetHitEffectOrigin, 0, 749 }, // [360]
    { FsmActionType::BoolTest, 0, 749 }, // [361]
    { FsmActionType::SetBoolValue, 0, 752 }, // [362]
    { FsmActionType::Noop, 0, 754 }, // [363]
    { FsmActionType::Noop, 0, 754 }, // [364]
    { FsmActionType::SetPosition2d, 0, 754 }, // [365]
    { FsmActionType::Noop, 0, 756 }, // [366]
    { FsmActionType::DamageHeroDirectly, 0, 756 }, // [367]
    { FsmActionType::Noop, 0, 757 }, // [368]
    { FsmActionType::FaceObjectV2, 0, 757 }, // [369]
    { FsmActionType::Noop, 0, 758 }, // [370]
    { FsmActionType::SetSpecialDeath, 0, 758 }, // [371]
    { FsmActionType::SetVelocity2d, 0, 759 }, // [372]
    { FsmActionType::Noop, 0, 761 }, // [373]
    { FsmActionType::Noop, 0, 761 }, // [374]
    { FsmActionType::SetDamageHeroAmount, 0, 761 }, // [375]
    { FsmActionType::Noop, 0, 762 }, // [376]
    { FsmActionType::Noop, 0, 762 }, // [377]
    { FsmActionType::Noop, 0, 762 }, // [378]
    { FsmActionType::Noop, 0, 762 }, // [379]
    { FsmActionType::Noop, 0, 762 }, // [380]
    { FsmActionType::FaceObjectV2, 0, 762 }, // [381]
    { FsmActionType::Noop, 0, 763 }, // [382]
    { FsmActionType::Noop, 0, 763 }, // [383]
    { FsmActionType::FloatAdd, 1, 763 }, // [384]
    { FsmActionType::FloatCompare, 0, 765 }, // [385]
    { FsmActionType::SendEventByName, 0, 771 }, // [386]
    { FsmActionType::Noop, 0, 773 }, // [387]
    { FsmActionType::SetHitboxGeometry, 0, 773 }, // [388]
    { FsmActionType::SetVelocity2d, 0, 778 }, // [389]
    { FsmActionType::Wait, 1, 780 }, // [390]
    { FsmActionType::SetIntValue, 0, 782 }, // [391]
    { FsmActionType::SendEventByScale, 0, 784 }, // [392]
    { FsmActionType::SetIntValue, 0, 786 }, // [393]
    { FsmActionType::CheckAlertRangeByName, 1, 788 }, // [394]
    { FsmActionType::Wait, 1, 793 }, // [395]
    { FsmActionType::Noop, 0, 795 }, // [396]
    { FsmActionType::FaceObjectV2, 0, 795 }, // [397]
    { FsmActionType::SetHitboxGeometry, 0, 796 }, // [398]
    { FsmActionType::Noop, 0, 801 }, // [399]
    { FsmActionType::Noop, 0, 801 }, // [400]
    { FsmActionType::FaceObjectV2, 0, 801 }, // [401]
    { FsmActionType::SetHitboxGeometry, 0, 802 }, // [402]
    { FsmActionType::Noop, 0, 807 }, // [403]
    { FsmActionType::Noop, 0, 807 }, // [404]
    { FsmActionType::SetHitboxGeometry, 0, 807 }, // [405]
    { FsmActionType::Wait, 1, 812 }, // [406]
    { FsmActionType::Noop, 0, 814 }, // [407]
    { FsmActionType::SetHitboxGeometry, 0, 814 }, // [408]
    { FsmActionType::GetXDistance, 1, 819 }, // [409]
    { FsmActionType::FloatCompare, 0, 820 }, // [410]
    { FsmActionType::FaceObjectV2, 0, 826 }, // [411]
    { FsmActionType::Noop, 0, 827 }, // [412]
    { FsmActionType::Noop, 0, 827 }, // [413]
    { FsmActionType::SetHitboxGeometry, 0, 827 }, // [414]
    { FsmActionType::Noop, 0, 832 }, // [415]
    { FsmActionType::SetVelocity2d, 0, 832 }, // [416]
    { FsmActionType::SetHitboxGeometry, 0, 834 }, // [417]
    { FsmActionType::Wait, 1, 839 }, // [418]
    { FsmActionType::SetHitboxGeometry, 0, 841 }, // [419]
    { FsmActionType::FaceObjectV2, 0, 846 }, // [420]
    { FsmActionType::Noop, 0, 847 }, // [421]
    { FsmActionType::CheckAlertRange, 1, 847 }, // [422]
    { FsmActionType::SetInvincible, 0, 852 }, // [423]
    { FsmActionType::WaitRandom, 1, 855 }, // [424]
    { FsmActionType::PreventInvincibleEffect, 0, 858 }, // [425]
    { FsmActionType::SetHitboxGeometry, 0, 859 }, // [426]
    { FsmActionType::Wait, 1, 864 }, // [427]
    { FsmActionType::SetHitboxGeometry, 0, 866 }, // [428]
    { FsmActionType::FaceObjectV2, 0, 871 }, // [429]
    { FsmActionType::SetVelocityByScale, 0, 872 }, // [430]
    { FsmActionType::Wait, 1, 874 }, // [431]
    { FsmActionType::Noop, 0, 876 }, // [432]
    { FsmActionType::Noop, 0, 876 }, // [433]
    { FsmActionType::SetHitboxGeometry, 0, 876 }, // [434]
    { FsmActionType::SetVelocity2d, 0, 881 }, // [435]
    { FsmActionType::Wait, 1, 883 }, // [436]
    { FsmActionType::SetHitboxGeometry, 0, 885 }, // [437]
    { FsmActionType::SetInvincible, 0, 890 }, // [438]
    { FsmActionType::PreventInvincibleEffect, 0, 893 }, // [439]
    { FsmActionType::SetHitboxGeometry, 0, 894 }, // [440]
    { FsmActionType::Wait, 1, 899 }, // [441]
    { FsmActionType::Noop, 0, 901 }, // [442]
    { FsmActionType::SetHitboxGeometry, 0, 901 }, // [443]
    { FsmActionType::CheckTargetDirection, 1, 906 }, // [444]
    { FsmActionType::CheckXPosition, 1, 916 }, // [445]
    { FsmActionType::BoolTestMulti, 1, 925 }, // [446]
    { FsmActionType::BoolTestMulti, 1, 931 }, // [447]
    { FsmActionType::DamageHeroDirectly, 0, 937 }, // [448]
    { FsmActionType::FaceObjectV2, 0, 938 }, // [449]
    { FsmActionType::Wait, 1, 939 }, // [450]
    { FsmActionType::SendEventByName, 0, 941 }, // [451]
    { FsmActionType::Noop, 0, 943 }, // [452]
    { FsmActionType::SetHitboxGeometry, 0, 943 }, // [453]
    { FsmActionType::Noop, 0, 948 }, // [454]
    { FsmActionType::CheckHeroPerformanceRegionV2, 1, 948 }, // [455]
    { FsmActionType::Wait, 1, 957 }, // [456]
    { FsmActionType::SetHitboxGeometry, 0, 959 }, // [457]
    { FsmActionType::SetVelocity2d, 0, 964 }, // [458]
    { FsmActionType::SendEventByName, 0, 966 }, // [459]
    { FsmActionType::SubtractHP, 0, 968 }, // [460]
    { FsmActionType::FreezeMoment, 0, 969 }, // [461]
    { FsmActionType::Noop, 0, 970 }, // [462]
    { FsmActionType::Noop, 0, 970 }, // [463]
    { FsmActionType::GetFsmFloat, 0, 970 }, // [464]
    { FsmActionType::FloatAdd, 1, 972 }, // [465]
    { FsmActionType::GetPosition2d, 0, 974 }, // [466]
    { FsmActionType::FloatClamp, 0, 976 }, // [467]
    { FsmActionType::SetPosition2d, 0, 979 }, // [468]
    { FsmActionType::Noop, 0, 981 }, // [469]
    { FsmActionType::SetGravity2dScale, 0, 981 }, // [470]
    { FsmActionType::Wait, 1, 982 }, // [471]
    { FsmActionType::SetRecoilBlocked, 0, 984 }, // [472]
    { FsmActionType::FaceObjectV2, 0, 988 }, // [473]
    { FsmActionType::Noop, 0, 989 }, // [474]
    { FsmActionType::Noop, 0, 989 }, // [475]
    { FsmActionType::SetSpecialDeath, 0, 989 }, // [476]
    { FsmActionType::SetHitboxGeometry, 0, 990 }, // [477]
    { FsmActionType::Noop, 0, 995 }, // [478]
    { FsmActionType::SetVelocity2d, 0, 995 }, // [479]
    { FsmActionType::SetDamageHeroAmount, 0, 997 }, // [480]
    { FsmActionType::DecelerateXY, 1, 998 }, // [481]
    { FsmActionType::Wait, 1, 1000 }, // [482]
    { FsmActionType::Noop, 0, 1002 }, // [483]
    { FsmActionType::Noop, 0, 1002 }, // [484]
    { FsmActionType::Noop, 0, 1002 }, // [485]
    { FsmActionType::SetHitboxGeometry, 0, 1002 }, // [486]
    { FsmActionType::Noop, 0, 1007 }, // [487]
    { FsmActionType::SetVelocity2d, 0, 1007 }, // [488]
    { FsmActionType::Wait, 1, 1009 }, // [489]
    { FsmActionType::SetHitboxGeometry, 0, 1011 }, // [490]
    { FsmActionType::SetPosition2d, 0, 1016 }, // [491]
    { FsmActionType::GetXDistance, 1, 1018 }, // [492]
    { FsmActionType::FloatCompare, 0, 1019 }, // [493]
    { FsmActionType::GetScale, 0, 1025 }, // [494]
    { FsmActionType::FloatMultiply, 0, 1028 }, // [495]
    { FsmActionType::Translate, 1, 1030 }, // [496]
    { FsmActionType::Wait, 1, 1033 }, // [497]
    { FsmActionType::SetHitboxGeometry, 0, 1035 }, // [498]
    { FsmActionType::SetGravity2dScale, 0, 1040 }, // [499]
    { FsmActionType::Noop, 0, 1041 }, // [500]
    { FsmActionType::Noop, 0, 1041 }, // [501]
    { FsmActionType::SendEventByName, 0, 1041 }, // [502]
    { FsmActionType::SetRecoilBlocked, 0, 1043 }, // [503]
    { FsmActionType::SetSpecialDeath, 0, 1047 }, // [504]
    { FsmActionType::SetDamageHeroAmount, 0, 1048 }, // [505]
    { FsmActionType::SetHitboxGeometry, 0, 1049 }, // [506]
    { FsmActionType::Noop, 0, 1054 }, // [507]
    { FsmActionType::SetGravity2dScale, 0, 1054 }, // [508]
    { FsmActionType::SetVelocityByScale, 0, 1055 }, // [509]
    { FsmActionType::Wait, 1, 1057 }, // [510]
    { FsmActionType::SetHitboxGeometry, 0, 1059 }, // [511]
    { FsmActionType::GetPosition2d, 0, 1064 }, // [512]
    { FsmActionType::FloatInRange, 0, 1066 }, // [513]
    { FsmActionType::Noop, 0, 1072 }, // [514]
    { FsmActionType::Noop, 0, 1072 }, // [515]
    { FsmActionType::FaceObjectV2, 0, 1072 }, // [516]
    { FsmActionType::GetXDistance, 1, 1073 }, // [517]
    { FsmActionType::FloatCompare, 0, 1074 }, // [518]
    { FsmActionType::FaceObjectV2, 0, 1080 }, // [519]
};

constexpr FsmTransitionDef TRANSITIONS[] = {
    { 1, 46 }, // [0] ATTACK -> CrossSlash?
    { 34, 46 }, // [1] TOOK DAMAGE -> CrossSlash?
    { 9, 12 }, // [2] COUNTER -> Counter Antic
    { 27, 70 }, // [3] RANGE OUT -> Evade 2
    { 30, 76 }, // [4] SING -> Sing Antic
    { 25, 59 }, // [5] NEXT -> Charge Break
    { 25, 3 }, // [6] NEXT -> Charge Recover
    { 0, 38 }, // [7] FINISHED -> Will Counter?
    { 25, 5 }, // [8] NEXT -> J Slash 1
    { 0, 7 }, // [9] FINISHED -> J Slash 2
    { 0, 10 }, // [10] FINISHED -> Downstab
    { 0, 8 }, // [11] FINISHED -> J Slash 3
    { 0, 9 }, // [12] FINISHED -> J Slash 4
    { 0, 86 }, // [13] FINISHED -> Dstab Constrain?
    { 21, 11 }, // [14] LAND -> Downstab Land
    { 38, 85 }, // [15] WALL -> Wallcling
    { 0, 38 }, // [16] FINISHED -> Will Counter?
    { 38, 85 }, // [17] WALL -> Wallcling
    { 0, 60 }, // [18] FINISHED -> Counter Dir
    { 12, 14 }, // [19] END -> Counter End
    { 3, 15 }, // [20] BLOCKED HIT -> Counter Hit
    { 0, 54 }, // [21] FINISHED -> Pose
    { 0, 16 }, // [22] FINISHED -> RapidSlash Charge
    { 0, 17 }, // [23] FINISHED -> RapidSlash Loop
    { 17, 53 }, // [24] HERO COLLIDE -> Collide To Multihit
    { 0, 18 }, // [25] FINISHED -> RapidSlash End
    { 24, 52 }, // [26] MULTI HIT CONNECT -> Hero Facing
    { 0, 54 }, // [27] FINISHED -> Pose
    { 0, 20 }, // [28] FINISHED -> ComboSlash 2
    { 0, 21 }, // [29] FINISHED -> ComboSlash 3
    { 0, 22 }, // [30] FINISHED -> ComboSlash 4
    { 0, 23 }, // [31] FINISHED -> ComboSlash 5
    { 0, 38 }, // [32] FINISHED -> Will Counter?
    { 6, 25 }, // [33] CLOSE -> Close
    { 15, 26 }, // [34] FAR -> Far
    { 30, 76 }, // [35] SING -> Sing Antic
    { 14, 27 }, // [36] EVADE -> Evade
    { 9, 12 }, // [37] COUNTER -> Counter Antic
    { 20, 1 }, // [38] J SLASH -> Charge Antic
    { 7, 19 }, // [39] COMBO -> ComboSlash 1
    { 5, 31 }, // [40] CHARGE -> Hop To Charge
    { 20, 32 }, // [41] J SLASH -> Hop To J Slash
    { 7, 33 }, // [42] COMBO -> Hop To Combo
    { 0, 28 }, // [43] FINISHED -> Evade Recover
    { 0, 29 }, // [44] FINISHED -> Evade Move
    { 20, 4 }, // [45] J SLASH -> J Slash Antic
    { 5, 1 }, // [46] CHARGE -> Charge Antic
    { 7, 33 }, // [47] COMBO -> Hop To Combo
    { 10, 47 }, // [48] CROSS SLASH -> CrossSlash Aim
    { 18, 34 }, // [49] HOP END -> Hop End
    { 0, 35 }, // [50] FINISHED -> Hop Antic
    { 0, 30 }, // [51] FINISHED -> Hop Check
    { 0, 30 }, // [52] FINISHED -> Hop Check
    { 0, 30 }, // [53] FINISHED -> Hop Check
    { 5, 1 }, // [54] CHARGE -> Charge Antic
    { 20, 4 }, // [55] J SLASH -> J Slash Antic
    { 7, 19 }, // [56] COMBO -> ComboSlash 1
    { 0, 36 }, // [57] FINISHED -> Hop
    { 0, 37 }, // [58] FINISHED -> Hop Recover
    { 0, 30 }, // [59] FINISHED -> Hop Check
    { 0, 54 }, // [60] FINISHED -> Pose
    { 0, 40 }, // [61] FINISHED -> Stun Air
    { 21, 56 }, // [62] LAND -> Stun Land
    { 12, 42 }, // [63] END -> Stun Recover
    { 34, 57 }, // [64] TOOK DAMAGE -> Stun Damage
    { 30, 76 }, // [65] SING -> Sing Antic
    { 0, 54 }, // [66] FINISHED -> Pose
    { 1, 44 }, // [67] ATTACK -> CrossSlash
    { 25, 55 }, // [68] NEXT -> Finish Multihit
    { 25, 54 }, // [69] NEXT -> Pose
    { 10, 47 }, // [70] CROSS SLASH -> CrossSlash Aim
    { 0, 24 }, // [71] FINISHED -> Distance Check
    { 0, 43 }, // [72] FINISHED -> CrossSlash Antic
    { 14, 48 }, // [73] EVADE -> CS Evade
    { 0, 27 }, // [74] FINISHED -> Evade
    { 12, 49 }, // [75] END -> CS Evade Cancel
    { 0, 43 }, // [76] FINISHED -> CrossSlash Antic
    { 0, 51 }, // [77] FINISHED -> Multihit Slash
    { 0, 54 }, // [78] FINISHED -> Pose
    { 0, 50 }, // [79] FINISHED -> Multihitting
    { 0, 52 }, // [80] FINISHED -> Hero Facing
    { 4, 67 }, // [81] CANCEL -> Collide Cancel
    { 2, 75 }, // [82] BIND BELL -> Bind Bell Damage
    { 0, 0 }, // [83] FINISHED -> Idle
    { 33, 61 }, // [84] SWISH -> Pose Swish
    { 22, 62 }, // [85] LEAN -> Pose Lean
    { 35, 63 }, // [86] UPRIGHT -> Pose Upright
    { 19, 65 }, // [87] HORNET DEAD -> Death Pose
    { 0, 45 }, // [88] FINISHED -> Slash Slam
    { 0, 41 }, // [89] FINISHED -> Stunned
    { 0, 41 }, // [90] FINISHED -> Stunned
    { 12, 58 }, // [91] END -> Damage Recover
    { 0, 42 }, // [92] FINISHED -> Stun Recover
    { 25, 2 }, // [93] NEXT -> Charge
    { 0, 13 }, // [94] FINISHED -> Counter Stance
    { 0, 64 }, // [95] FINISHED -> Pose Swish 2
    { 4, 62 }, // [96] CANCEL -> Pose Lean
    { 0, 0 }, // [97] FINISHED -> Idle
    { 0, 0 }, // [98] FINISHED -> Idle
    { 0, 0 }, // [99] FINISHED -> Idle
    { 14, 0 }, // [100] EVADE -> Idle
    { 0, 0 }, // [101] FINISHED -> Idle
    { 0, 17 }, // [102] FINISHED -> RapidSlash Loop
    { 26, 72 }, // [103] RANGE IN -> Range Return
    { 3, 73 }, // [104] BLOCKED HIT -> Swish Block
    { 36, 73 }, // [105] WAIT -> Swish Block
    { 0, 0 }, // [106] FINISHED -> Idle
    { 0, 71 }, // [107] FINISHED -> Evade Recover 2
    { 0, 74 }, // [108] FINISHED -> Keep Evading?
    { 0, 46 }, // [109] FINISHED -> CrossSlash?
    { 0, 68 }, // [110] FINISHED -> Range Out
    { 14, 70 }, // [111] EVADE -> Evade 2
    { 0, 68 }, // [112] FINISHED -> Range Out
    { 0, 18 }, // [113] FINISHED -> RapidSlash End
    { 0, 77 }, // [114] FINISHED -> Sing
    { 12, 78 }, // [115] END -> Sing End
    { 31, 78 }, // [116] SING DURATION END -> Sing End
    { 0, 38 }, // [117] FINISHED -> Will Counter?
    { 0, 80 }, // [118] FINISHED -> Lava Hop
    { 0, 81 }, // [119] FINISHED -> Lava Tele Out
    { 0, 82 }, // [120] FINISHED -> Set Tele Pos X
    { 0, 83 }, // [121] FINISHED -> Tele In
    { 0, 84 }, // [122] FINISHED -> Lava End
    { 0, 0 }, // [123] FINISHED -> Idle
    { 0, 87 }, // [124] FINISHED -> Kickoff
    { 0, 6 }, // [125] FINISHED -> Downstab Antic
    { 0, 5 }, // [126] FINISHED -> J Slash 1
};

constexpr float PARAMS[] = {
    0.75f, 1.0f, 1.0f, 0.0f, 10002.0f, 0.0f, 1.0f, 10001.0f,
    1.0f, 0.0f, 0.0f, 0.0f, 255.0f, 10002.0f, 6.0f, 0.0f,
    0.0f, 10512.0f, 0.0f, 10001.0f, 0.25f, 0.0f, 0.0f, 0.0f,
    10513.0f, 9.0f, NAN, 2.0f, 10512.0f, 10513.0f, 0.0f, 255.0f,
    0.0f, 27.0f, 0.0f, 0.0f, 0.20000000298023224f, 0.20000000298023224f, 255.0f, 30.0f,
    255.0f, 1.0f, 0.0f, 0.0f, 0.5833333333333334f, 1.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 1.0f, -32.0f, NAN, 0.824999988079071f, NAN,
    0.20000000298023224f, 25.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 80.0f,
    NAN, 0.30000001192092896f, 25.0f, 0.8899999856948853f, NAN, 1.14f, 0.77f, 1.85f,
    -0.65f, 1.0f, 10515.0f, 1.0f, 0.16666666666666666f, 0.0f, 0.875f, NAN,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.6499999761581421f, 25.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.1111111111111111f, 0.0f, 0.0f,
    60.0f, 87.0f, 0.824999988079071f, 0.824999988079071f, 1.74f, 2.37f, 0.47f, -0.59f,
    1.0f, 1.0f, 0.824999988079071f, 0.824999988079071f, 0.5f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.1111111111111111f, 0.0f, 0.824999988079071f, 0.824999988079071f, 1.74f,
    2.37f, 0.47f, -0.59f, 1.0f, 0.1111111111111111f, 0.0f, 0.824999988079071f, 0.824999988079071f,
    1.74f, 2.37f, 0.47f, -0.59f, 1.0f, 0.2777777777777778f, 0.0f, 0.824999988079071f,
    0.824999988079071f, 2.19f, 1.44f, -0.02f, 1.34f, 1.0f, 45.0f, -45.0f,
    0.20000000298023224f, 21.0f, 255.0f, 255.0f, 255.0f, 21.0f, 255.0f, 1.0f,
    1.0f, 255.0f, 255.0f, 10529.0f, 0.0f, 0.0f, 255.0f, 255.0f,
    255.0f, 255.0f, 10528.0f, 0.0f, 0.0f, 0.0f, 0.0f, -0.75f,
    38.0f, NAN, 2.0f, 10529.0f, 10528.0f, 10005.0f, 0.0f, 0.0f,
    255.0f, 0.0f, 255.0f, 10530.0f, 255.0f, 0.0f, 38.0f, NAN,
    1.0f, 10530.0f, 0.74f, 1.03f, 0.87f, -0.98f, 1.0f, 10006.0f,
    NAN, 10006.0f, 81.0f, 107.0f, NAN, 255.0f, 38.0f, NAN,
    10005.0f, 10003.0f, 0.26666666666666666f, 0.0f, 0.0f, 0.0f, 0.800000011920929f, NAN,
    10515.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 10522.0f,
    0.0f, 1.0f, 0.16666666666666666f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 1.0f, 10263.0f, 0.0f, 0.75f, 12.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.2f, 0.0f, 10515.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.25f, 0.0f, 1.74f,
    2.37f, 0.47f, -0.59f, 1.0f, 0.16666666666666666f, 0.0f, 19.0f, NAN,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.75f, NAN,
    0.6499999761581421f, 0.0f, 255.0f, 0.0f, 1.0f, 0.0f, 1.79f, 1.03f,
    0.24f, 0.59f, 1.0f, 0.26666666666666666f, 0.0f, 1.0f, 10515.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.125f, 0.0f,
    2.96f, 1.83f, 1.08f, 0.69f, 1.0f, 30.0f, NAN, 0.08333333333333333f,
    0.0f, 3.09f, 1.42f, 0.58f, 0.56f, 1.0f, 0.125f, 0.0f,
    0.800000011920929f, NAN, 2.96f, 1.83f, 1.08f, 0.69f, 1.0f, 30.0f,
    NAN, 0.08333333333333333f, 0.0f, 3.09f, 1.42f, 0.58f, 0.56f, 1.0f,
    1.1666666666666667f, 0.0f, 10515.0f, 1.0f, 0.800000011920929f, NAN, 2.96f, 1.83f,
    1.08f, 0.69f, 1.0f, 0.0f, 0.0f, 0.0f, 255.0f, 30.0f,
    255.0f, 1.0f, 0.0f, 0.0f, 10002.0f, 10002.0f, 6.0f, 0.0f,
    6.0f, 6.0f, 15.0f, 0.0f, 20.0f, 0.0f, 255.0f, 0.0f,
    3.0f, 14.0f, 7.0f, 20.0f, 1.0f, 1.0f, 1.0f, 2.0f,
    2.0f, 2.0f, 4.0f, 4.0f, 4.0f, 10262.0f, 0.0f, 0.0f,
    20.0f, 0.0f, 255.0f, 0.0f, 3.0f, 7.0f, 5.0f, 20.0f,
    1.0f, 1.0f, 1.0f, 2.0f, 1.0f, 2.0f, 4.0f, 4.0f,
    4.0f, 1.0f, -30.0f, NAN, 0.2f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.4666666666666667f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 10523.0f, 10.0f, 255.0f, 3.0f,
    7.0f, 5.0f, 20.0f, 1.0f, 1.0f, 1.0f, 10002.0f, 10002.0f,
    10008.0f, 0.0f, 18.0f, 18.0f, 255.0f, 0.0f, 0.0f, 0.0f,
    255.0f, 0.0f, 10262.0f, 3.0f, 255.0f, 255.0f, 18.0f, 10008.0f,
    16.0f, 10269.0f, 5.0f, 10008.0f, 12.0f, 10269.0f, 20.0f, 10008.0f,
    9.25f, 10269.0f, 7.0f, 255.0f, 0.0f, 10269.0f, 0.0f, 10262.0f,
    1.0f, 1.0f, 0.25f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 24.0f, NAN, 0.13333333333333333f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.3333333333333333f, 0.0f, 0.75f, NAN, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 2.0f, 255.0f, 0.0f, 0.33000001311302185f, 0.6600000262260437f,
    10522.0f, 1.0f, 7.0f, 10007.0f, 2.0f, 10003.0f, 1.0f, -6.0f,
    23.0f, 0.0f, 0.0f, 0.0f, 255.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 255.0f, 255.0f, 21.0f, 255.0f, 255.0f,
    255.0f, 21.0f, 255.0f, 0.0f, 1.0f, 0.8500000238418579f, NAN, 10007.0f,
    -1.0f, 10007.0f, 0.0f, 0.0f, 12.0f, 12.0f, 255.0f, 0.0f,
    0.5f, 0.5f, 255.0f, 30.0f, 255.0f, 0.0f, 0.0f, 0.0f,
    15.0f, 255.0f, 0.0f, 0.2f, 0.0f, 10515.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 10261.0f, 0.0f, 255.0f, 0.0f,
    2.0f, 4.0f, 10258.0f, 0.0f, 0.0f, 255.0f, 0.0f, 0.8999999761581421f,
    1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f,
    0.0f, 0.0f, 0.800000011920929f, 25.0f, 255.0f, 0.0f, NAN, NAN,
    2.19f, 1.44f, 0.0f, 0.0f, 1.0f, 0.0f, -0.30000001192092896f, 0.0f,
    255.0f, 0.009999999776482582f, 15.0f, 0.0f, 0.2f, 25.0f, 0.0f, 1.0f,
    0.0f, 255.0f, 0.0f, 10515.0f, 1.0f, 0.74f, 1.03f, 0.87f,
    -0.98f, 1.0f, 10268.0f, 255.0f, 255.0f, 0.0f, 10258.0f, 0.0f,
    10.0f, 10.0f, 255.0f, 10258.0f, -1.0f, 10523.0f, 0.0f, 1.0f,
    10002.0f, 10002.0f, 6.0f, 0.0f, 255.0f, 14.0f, 255.0f, 10006.0f,
    NAN, 10006.0f, 10000.0f, 0.0f, 0.0f, 0.0f, 10521.0f, 10009.0f,
    0.0f, 0.0f, 10009.0f, 0.0f, 0.0f, 0.0f, 0.0f, 10516.0f,
    14.0f, 255.0f, NAN, 1.0f, 10521.0f, 10516.0f, 14.0f, 255.0f,
    NAN, 1.0f, 10521.0f, 10516.0f, 10523.0f, 1.0f, 10261.0f, 1.0f,
    10261.0f, 2.0f, 12.0f, 255.0f, 12.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 1.0f, 10006.0f, NAN, 10006.0f, 10000.0f, 0.0f,
    255.0f, 0.0f, 255.0f, -1.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, NAN, NAN, 0.15000000596046448f,
    0.0f, 0.0f, 0.0f, 255.0f, 0.75f, 0.0f, 2.86f, 1.2f,
    2.85f, -0.1f, 1.0f, 0.0f, 0.5f, 0.0f, 0.4166666666666667f, 0.0f,
    1.0f, 255.0f, 0.0f, 1.0f, 10515.0f, 1.0f, 2.86f, 1.2f,
    2.85f, -0.1f, 1.0f, 255.0f, 255.0f, 255.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 10524.0f, 2.0f, 255.0f,
    255.0f, 4.0f, 255.0f, 0.0f, 255.0f, 0.0f, 2.86f, 1.2f,
    2.85f, -0.1f, 1.0f, 10518.0f, 19.0f, 255.0f, 10515.0f, 255.0f,
    0.0f, 3.0f, 33.0f, 22.0f, 35.0f, 1.0f, 1.0f, 1.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 10514.0f, 255.0f, 0.0f,
    10514.0f, 0.0f, NAN, NAN, 1.0f, 1.0f, 0.0f, 0.0f,
    0.0f, 1.0f, 1.0f, 10007.0f, -0.25f, 10007.0f, 0.0f, 0.0f,
    12.0f, 12.0f, 0.0f, 255.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.6000000238418579f, 25.0f, 10263.0f, 9.0f,
    0.0f, 255.0f, 10263.0f, 8.0f, 0.0f, 255.0f, 0.0f, 255.0f,
    0.0f, 0.06666666666666667f, 0.0f, 1.0f, 1.79f, 1.03f, 0.24f, 0.59f,
    1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.06666666666666667f, 0.0f, 1.79f, 1.03f,
    0.24f, 0.59f, 1.0f, 10002.0f, 10002.0f, 2.0f, 0.0f, 255.0f,
    14.0f, 255.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.4666666666666667f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f,
    26.0f, 0.0f, 255.0f, 0.0f, 1.0f, 0.0f, 0.0f, 4.0f,
    8.0f, 36.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.06666666666666667f, 0.0f, 1.79f, 1.03f, 0.24f, 0.59f, 1.0f, 1.0f,
    -30.0f, NAN, 0.2f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.4666666666666667f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.26666666666666666f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 255.0f, 255.0f, 255.0f, 255.0f, 0.0f, 0.0f,
    10517.0f, 0.0f, 0.0f, 0.0f, 10000.0f, 0.0f, 0.0f, 255.0f,
    0.0f, 255.0f, 0.0f, 255.0f, 10519.0f, 14.0f, 255.0f, NAN,
    1.0f, 10517.0f, 10519.0f, 14.0f, 0.0f, NAN, 1.0f, 10517.0f,
    10519.0f, 1.0f, 1.0f, 0.16666666666666666f, 0.0f, 255.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.5f, 0.5f, 12.0f,
    255.0f, 255.0f, 1.0f, 0.0f, 0.0f, 0.16666666666666666f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 255.0f, 0.0f,
    40.0f, 0.0f, 10010.0f, -0.5f, 10010.0f, 0.20000000298023224f, 10006.0f, NAN,
    10006.0f, 79.0f, 109.0f, 10006.0f, 10010.0f, 0.0f, 0.8500000238418579f, 0.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 80.0f, 1.0f, NAN, 0.8500000238418579f,
    0.4000000059604645f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.25f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    10000.0f, 10005.0f, 10002.0f, 10002.0f, 3.0f, 0.0f, 255.0f, 255.0f,
    0.0f, 10009.0f, 0.0f, 0.0f, 10009.0f, 8.0f, 10009.0f, 0.0f,
    0.0f, 0.35f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    10003.0f, 255.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 30.0f,
    NAN, 0.26666666666666666f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    10006.0f, NAN, 10006.0f, 86.0f, 102.0f, NAN, 255.0f, 0.0f,
    1.0f, 10002.0f, 10002.0f, 2.0f, 0.0f, 255.0f, 255.0f, 0.0f,
    0.0f,
};

constexpr FsmTransitionDef GLOBAL_TRANSITIONS[] = {
    { 32, 39 }, // STUN -> Stun Start
    { 37, 79 }, // LAVA DAMAGE -> Lava Damage
};

// State name table (debug only)
constexpr const char* STATE_NAMES[] = {
    "Idle",
    "Charge Antic",
    "Charge",
    "Charge Recover",
    "J Slash Antic",
    "J Slash 1",
    "Downstab Antic",
    "J Slash 2",
    "J Slash 3",
    "J Slash 4",
    "Downstab",
    "Downstab Land",
    "Counter Antic",
    "Counter Stance",
    "Counter End",
    "Counter Hit",
    "RapidSlash Charge",
    "RapidSlash Loop",
    "RapidSlash End",
    "ComboSlash 1",
    "ComboSlash 2",
    "ComboSlash 3",
    "ComboSlash 4",
    "ComboSlash 5",
    "Distance Check",
    "Close",
    "Far",
    "Evade",
    "Evade Recover",
    "Evade Move",
    "Hop Check",
    "Hop To Charge",
    "Hop To J Slash",
    "Hop To Combo",
    "Hop End",
    "Hop Antic",
    "Hop",
    "Hop Recover",
    "Will Counter?",
    "Stun Start",
    "Stun Air",
    "Stunned",
    "Stun Recover",
    "CrossSlash Antic",
    "CrossSlash",
    "Slash Slam",
    "CrossSlash?",
    "CrossSlash Aim",
    "CS Evade",
    "CS Evade Cancel",
    "Multihitting",
    "Multihit Slash",
    "Hero Facing",
    "Collide To Multihit",
    "Pose",
    "Finish Multihit",
    "Stun Land",
    "Stun Damage",
    "Damage Recover",
    "Charge Break",
    "Counter Dir",
    "Pose Swish",
    "Pose Lean",
    "Pose Upright",
    "Pose Swish 2",
    "Death Pose",
    "Trap Stun",
    "Collide Cancel",
    "Range Out",
    "Pose Swish 3",
    "Evade 2",
    "Evade Recover 2",
    "Range Return",
    "Swish Block",
    "Keep Evading?",
    "Bind Bell Damage",
    "Sing Antic",
    "Sing",
    "Sing End",
    "Lava Damage",
    "Lava Hop",
    "Lava Tele Out",
    "Set Tele Pos X",
    "Tele In",
    "Lava End",
    "Wallcling",
    "Dstab Constrain?",
    "Kickoff",
};

// Build the FsmDef struct (copies into inline arrays for GPU compat)
inline FsmDef makeDef() {
    FsmDef def{};
    static_assert(88 <= FSM_MAX_STATES);
    static_assert(520 <= FSM_MAX_TOTAL_ACTIONS);
    static_assert(127 <= FSM_MAX_TRANSITIONS);
    static_assert(1081 <= FSM_MAX_PARAMS);
    static_assert(2 <= FSM_MAX_GLOBAL_TRANSITIONS);
    for (int i = 0; i < 88; ++i) def.states[i] = STATES[i];
    for (int i = 0; i < 520; ++i) def.actions[i] = ACTIONS[i];
    for (int i = 0; i < 127; ++i) def.transitions[i] = TRANSITIONS[i];
    for (int i = 0; i < 1081; ++i) def.params[i] = PARAMS[i];
    for (int i = 0; i < 2; ++i) def.globalTransitions[i] = GLOBAL_TRANSITIONS[i];
    def.numStates = 88;
    def.numActions = 520;
    def.numTransitions = 127;
    def.numParams = 1081;
    def.numFloatVars = 17;
    def.numIntVars = 14;
    def.numBoolVars = 19;
    def.numGlobalTransitions = 2;
    def.startState = 0;
    for (int i = 0; i < 17; ++i) def.initFloatVars[i] = INIT_FLOAT_VARS[i];
    for (int i = 0; i < 14; ++i) def.initIntVars[i] = INIT_INT_VARS[i];
    for (int i = 0; i < 19; ++i) def.initBoolVars[i] = INIT_BOOL_VARS[i];
    return def;
}

} // namespace fsm_lace_boss1
} // namespace silksong

